### ISSUE TITLE
Add a warning about Symbol Interning of User Input

### ISSUE THREAD

**Issue by estsauver** [intridea/multi_json#155]
Hey MultiJson, 

It seems like the readme should include a reference to the dangers of interning user supplied strings. Adding a "symbolize_keys" flag to your endpoints can lead to DDOS vulnerabilities if user supplied input is ever parsed.

http://www.ruby-doc.org/core-2.2.0/doc/security_rdoc.html#label-Symbols

~Earl

**Comment by rwz** [comment]
Well, that should be pretty obvious even without mentioning. Do we really want to include these sort of warnings each time some code calls `to_sym` on input? I don't think so.
