### ISSUE TITLE
"indent" argument causing TypeError with pure Ruby backend

### ISSUE THREAD

**Issue by twelve17** [intridea/multi_json#159]
I'm working on a legacy project which uses pure ruby JSON (e.g. `MultiJson::Adapters::JsonGem`), and I am getting a TypeError with multi_json:

```
[17] pry(main)> MultiJson.use('json_gem')
=> MultiJson::Adapters::JsonGem
[18] pry(main)> MultiJson.dump({:abc => 'def'}, indent: 2)
TypeError: wrong argument type Fixnum (expected String)
from /.../lib/ruby/gems/1.9.1/gems/multi_json-1.11.1/lib/multi_json/adapters/json_common.rb:19:in `initialize'
```` 

Using a string for the value of `indent` works as expected:
```
[19] pry(main)> MultiJson.dump({:abc => 'def'}, indent: "2")
=> "{2\"abc\":\"def\"}"
```

My guess is that [this commit for OJ](https://github.com/intridea/multi_json/commit/826fc5535b863b74fc9f981dfdda3e26f1ee4e5b) maybe broke this.

Although OJ requires `indent` to be a Fixnum, Ruby's JSON implementation [requires it to be a string](https://github.com/ruby/ruby/blob/ruby_2_0_0/ext/json/lib/json/common.rb#L193).  Fun!

Maybe multi_json can convert opts as appropriate depending on the underlying adapter?

**Comment by rwz** [comment]
I've poked around a little bit and realized that there's no way to make adapters support unified indent option. First of all, some adapters just don't have these feature. The ones that do, apply indentation differently.

For example, `indent: 2` looks like this on Oj:
```
{
  "foo": "bar"
}
```

Ruby JSON gem with two-space indent produces this:
```
{  "foo": "bar"}
```

How does that makes sense? ¯\\\_(ツ)\_/¯
