### ISSUE TITLE
Consider upgrading JrJackson - version 0.3.2 now available

### ISSUE THREAD

**Issue by guyboertje** [intridea/multi_json#161]
I have released v0.3.2 of JrJackson.  Gemfile version specifier limits to 0.2.X

The JrJackson::Json API is backwards compatible but there are dramatic performance improvements in parse and generate.
The version change to 0.3.X is because I added 'OJ like' Streaming Doc to Object behaviour.

**Comment by rwz** [comment]
@guyboertje seems like [it's failing](https://travis-ci.org/intridea/multi_json/jobs/79519127) on current test suite.

**Comment by guyboertje** [comment]
@rwz - apologies. Please try version 0.3.4, test added and bug fixed.

**Comment by rwz** [comment]
@guyboertje yay, everything is awesome and green @ https://github.com/intridea/multi_json/commit/1ba3be42600696f676d9cc1f029227b84c3c763b
