### ISSUE TITLE
 Missing spec/ in gem v1.11.2 in rubygems.org 

### ISSUE THREAD

**Issue by paramite** [intridea/multi_json#162]
Greetings,
  
  most recent gem [1] is missing spec/ directory. Would you be so kind and fix that please?

Thanks in advance!

 [1] https://rubygems.org/gems/multi_json/versions/1.11.2

**Comment by rwz** [comment]
That's intentional. There's no real reason to ship specs with the gem itself.

**Comment by paramite** [comment]
Actually there is. When we are packaging gem to rpm, we run test suite to be sure that the package is functional. But ok, I will go another way around.

**Comment by rwz** [comment]
Interesting approach. MultiJson's tests are always passing at least at the moment of release, that I can tell you.

We also tag all our releases on github, so if you need specs desperately, you can get them from https://github.com/intridea/multi_json/tree/v1.11.2/spec
