### ISSUE TITLE
Seems like MultiJson doesn't respect Oj default_options

### ISSUE THREAD

**Issue by quentindemetz** [intridea/multi_json#163]
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
oj (2.13.1)
multi_json (1.11.2)
```ruby
$ require 'oj'
$ require 'multi_json'
$ Oj.default_options = {mode: :null}
$ MultiJson.dump(foo: Float::INFINITY)
=> "{"foo":Infinity}"
$ Oj.dump(foo: Float::INFINITY)
TypeError: In :strict mode all Hash keys must be Strings, not Symbol.

        from (irb):6:in `dump'
        from (irb):6
        from /usr/bin/irb:11:in `<main>'
```
Is this expected behaviour ?
Thanks

**Comment by quentindemetz** [comment]
Looks like it's actually hard-coded in the code, but differences between encoders actually leak out of MultiJson. The following doesn't behave the same with yajl-ruby or oj:
```
MultiJson.dump(foo: Float::INFINITY)
# fails with yajl
# "Infinity" with Oj
```

**Comment by rwz** [comment]
Well, MultiJson can't really address slight differences in edge-case behavior like this without significant performance penalty. I guess the idea is that you're responsible for preventing Infinity from leaking into your data structures before passing it to MultiJson.

Sorry, I know that doesn't help much, but we're trying to keep MultiJson fairly simple narrow scoped. :)
