### ISSUE TITLE
make.exe: *** fatal error in forked process 

### ISSUE THREAD

**Issue by luigiusai** [intridea/multi_json#171]
Dimmi: gem install json
Building native extensions.  This could take a while...
      2 [main] make 9596 C:\cygwin64\bin\make.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
   4076 [main] make 9596 cygwin_exception::open_stackdumpfile: Dumping stack trace to make.exe.stackdump
      3 [main] make 4904 fork: child -1 - forked process 9596 died unexpectedly, retry 0, exit code 0x100, errno 11
      2 [main] make 13280 C:\cygwin64\bin\make.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
   2846 [main] make 13280 cygwin_exception::open_stackdumpfile: Dumping stack trace to make.exe.stackdump
      4 [main] make 460 fork: child -1 - forked process 13280 died unexpectedly, retry 0, exit code 0x100, errno 11
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

```
current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/json-2.0.1/ext/json/ext/generator
```

C:/Ruby23/bin/ruby.exe -r ./siteconf20160725-13992-1jt6pec.rb extconf.rb
creating Makefile

current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/json-2.0.1/ext/json/ext/generator
make "DESTDIR=" clean
      2 [main] make 9596 C:\cygwin64\bin\make.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
   4076 [main] make 9596 cygwin_exception::open_stackdumpfile: Dumping stack trace to make.exe.stackdump
      3 [main] make 4904 fork: child -1 - forked process 9596 died unexpectedly, retry 0, exit code 0x100, errno 11
make: fork: Resource temporarily unavailable

current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/json-2.0.1/ext/json/ext/generator
make "DESTDIR="
      2 [main] make 13280 C:\cygwin64\bin\make.exe: **\* fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
   2846 [main] make 13280 cygwin_exception::open_stackdumpfile: Dumping stack trace to make.exe.stackdump
      4 [main] make 460 fork: child -1 - forked process 13280 died unexpectedly, retry 0, exit code 0x100, errno 11
make: fork: Resource temporarily unavailable

make failed, exit code 2

Gem files will remain installed in C:/Ruby23/lib/ruby/gems/2.3.0/gems/json-2.0.1 for inspection.
Results logged to C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/json-2.0.1/gem_make.out

Dimmi:

**Comment by rwz** [comment]
You're trying to install the gem `json` and getting an error. This is not the repo for the `json` gem.

Also, if you're on a 2+ version of ruby, you don't even need the gem. `json` stdlib is good enough for most cases.
