### ISSUE TITLE
MultiJSON.load throws JSON::ParserError instead of MultiJSON::ParseError

### ISSUE THREAD

**Issue by faucct** [intridea/multi_json#174]
Please, see https://github.com/ruby-json-schema/json-schema/issues/366

**Comment by rwz** [comment]
You're using `require 'oj_mimic_json'` which is not supported by MultiJson.

MultiJson supports Oj adapter natively, there's no need to load a hacky solution that makes Oj pretend to be stdlib JSON and break all sorts of expectations other code might have about it.
