### ISSUE TITLE
MultiJSON::ParseError occurs when a type integer property format is invalid

### ISSUE THREAD

**Issue by nextofsearch** [intridea/multi_json#175]
Hi,

Is this an intended behavior that MultiJSON::ParseError occurs when a integer-type property's format is invalid

```
{
  "customer_id": 002
}
```

**Comment by rwz** [comment]
We don't have any guidelines around malformed integers specifically, this behavior is up to the adapter. I expect most adapters to reject it and throw parse error.

Feel free to comment if you have further questions though.
