### ISSUE TITLE
to_json clobbers emoji

### ISSUE THREAD

**Issue by benhamill** [intridea/multi_json#176]
The `JsonGem` adapter uses `JsonCommon`, which called `to_json` in it's `dump` method. I recently discovered that this causes problems marshalling and unmarshalling emoji.

Behold:
```
2.2.5 :024 > x
 => {:message=>"👩👩‍🎤🎃😪😔😟😍😳😎🙏😀😕😀😏\u{1F921}🖐☺️😣👿😊"}
2.2.5 :025 > MultiJson.adapter
 => MultiJson::Adapters::JsonGem
2.2.5 :026 > MultiJson.dump(x)
 => "{\"message\":\"\\uf469\\u200d\\uf3a4\\uf383\\uf62a\\uf614\\uf61f\\uf60d\\uf633\\uf60e\\uf64f\\uf600\\uf615\\uf600\\uf60f\\uf921\\uf590\\u263a\\ufe0f\\uf623\\uf47f\\uf60a\"}"
2.2.5 :027 > MultiJson.load(MultiJson.dump(x))
 => {"message"=>"嵐☺️"}
```

I think this is just a one-line change in json_common.rb from `to_json` to `JSON.dump`. But maybe that's not true for all the things that use `JsonCommon`? Is this a change y'all would be interested in seeing?

**Comment by rwz** [comment]
I can't recreate this bug:

```
[4] pry(main)> MultiJson.adapter
=> MultiJson::Adapters::JsonGem
[5] pry(main)> x = {:message=>"👩👩‍🎤🎃😪😔😟😍😳😎🙏😀😕😀😏\u{1F921}🖐☺️😣👿😊"}
=> {:message=>"👩👩‍🎤🎃😪😔😟😍😳😎🙏😀😕😀😏🤡🖐☺️😣👿😊"}
[6] pry(main)> MultiJson.dump(x)
=> "{\"message\":\"👩👩‍🎤🎃😪😔😟😍😳😎🙏😀😕😀😏🤡🖐☺️😣👿😊\"}"
[7] pry(main)> MultiJson.load(MultiJson.dump(x))
=> {"message"=>"👩👩‍🎤🎃😪😔😟😍😳😎🙏😀😕😀😏🤡🖐☺️😣👿😊"}
```

What version of json gem are you using? Does ugrading the gem solves the issue for you?
