### ISSUE TITLE
Decode function not working as expected

### ISSUE THREAD

**Issue by abhijitkatiyar** [intridea/multi_json#187]
MultiJson.decode behaves abnormally while dealing with certain characters:
Example:
`MultiJson.decode("What’s") #=> "Whatâ\u0080\u0099s"`

While JSON.parse works just fine:
`JSON.parse("{\"id\" : \"What’s\"}") #=> {"id"=>"What’s"}` 

Same behaviour on both 1.13.1 and 1.12.1 with :gson adapter

**Comment by rwz** [comment]
This example you gave is super weird and should not be working at all on any adapter. This is what the expected behavior should be:

```
MultiJson.decode("What’s") # =>
# MultiJson::ParseError: 785: unexpected token at 'What’s'
# from /usr/local/bundle/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
# Caused by JSON::ParserError: 785: unexpected token at 'What’s'
# from /usr/local/bundle/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
```

AFAIK the gson.rb is an abandonware at this point and its author is not fixing any bugs. Feel free to send a PR if you can figure out how to fix it.
