### ISSUE TITLE
Where do security issues belong?

### ISSUE THREAD

**Issue by xxx** [intridea/multi_json#200]
Hi,

Who do I contact regarding potential vulnerabilities? I'd rather not just post it publicly, but will do so in a week if I don't hear anything. I have a failing spec that I believe should pass, which quickly shows what we're seeing.

This is on version 1.15.0

**Comment by rwz** [comment]
Hi,

MultiJSON is not being actively maintained, but if the issue is something that can be addressed relatively easily, I'll be happy to take a look.

Feel free to send the details to pavel@pravosud.com

**Comment by xxx** [comment]
closing this since contact has been made privately.

**Comment by yangqinglin** [comment]
same issue.
