### ISSUE TITLE
warning: BigDecimal.new is deprecated; use BigDecimal() method instead. in multi_json 1.15.0

### ISSUE THREAD

**Issue by hphucnp** [intridea/multi_json#207]
When I use elasticsearch-ruby 7.10.1 which use multi_json 1.15.0, I got the warning nearly every second, can we have this to be fixed because rails always complains this warning and it consumes all the logs space

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/14350997/199410396-6f109ac4-261a-4244-8175-c583d82d190f.png">

**Comment by matuszewskijan** [comment]
I believe it's not directly a `MultiJson` issue, as the `BigDecimal` is loaded from [`Oj`](https://github.com/ohler55/oj) adapter. Could you check if there is any `Oj` update available for you and if the warning is gone after the update?

**Comment by sferik** [comment]
@hphucnp Is this issue resolved now? I’m going to close this issue but please feel free to comment and reopen it if you believe this is still an issue with this library.
